project:
  type: book
  output-dir: docs

book:
  title: "Code Peer Review with GitHub"
  author: "Changemakers project team"
  date: "today"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-setup-for-teachers.qmd
    - 03-overview-for-teachers.qmd
    - 04-details-for-teachers.qmd
    - 05-overview-for-students.qmd
    - 06-setup-for-students.qmd
    - 07-FAQs.qmd

format:
  html:
    theme: cosmo